name: Job Alert

on:
  schedule:
    - cron: '30 3 * * 1-5'  # 09:00 AM IST = 03:30 UTC
  workflow_dispatch:

jobs:
  run-job-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run job scraper
        run: python main.py
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
